.TH SYSLOG-NAGIOS-BRIDGE 8
.SH NAME
syslog-nagios-bridge \- transfer SysLog events to Nagios
.SH SYNOPSIS
.B syslog-nagios-bridge
[\fBconfig-file\fR]
.SH DESCRIPTION
.B syslog-nagios-bridge
monitors SysLog events from the network and generates Nagios check results.
.SH OPTIONS
.TP
.BR config-file
Use a custom configuration file instead of the default.
